### ISSUE TITLE
[User][Model] Missing past_event and upcoming_event methods

### ISSUE THREAD

**Issue by heyapricot** [gferrarocamus/private-events#2]
From the project specification:
> 5. Modify the User’s Show page to separate those events which have occurred in the past (“Previously attended events”) from those which are occuring in the future (“Upcoming events”). You could do this by putting logic in your view. Don’t. Have your controller call separate model methods to retrieve each, e.g. @upcoming_events = current_user.upcoming_events and @prev_events = current_user.previous_events. You’ll get some practice with working with dates as well as building some queries.

**Comment by gferrarocamus** [comment]
Hi @heyapricot - thanks for the review! We've separated the attended events into "Previous events" and "Upcoming events" [here](https://github.com/gferrarocamus/private-events/blob/fe052c48be2fe515054880965c3192e3ee6aded9/app/views/users/show.html.erb). The logic for this is in [the corresponding controller](https://github.com/gferrarocamus/private-events/blob/fe052c48be2fe515054880965c3192e3ee6aded9/app/controllers/users_controller.rb):

```
  def show
    @user = current_user
    @previous_events = @user.attended_events.where('date < ?', Time.now.in_time_zone)
    @upcoming_events = @user.attended_events.where('date > ?', Time.now.in_time_zone)
  end
```

Is there anything else we should do about this?

Thanks!

**Comment by heyapricot** [comment]
I noticed it. The thing is, it goes against the [Fat Model, Skinny controller](https://www.sitepoint.com/10-ruby-on-rails-best-practices/)
